# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
language: r
sudo: required
warnings_are_errors: true

env:
 global:
   - CRAN: https://cran.rstudio.com

notifications:
  email:
    - jdunham@mit.edu
